# Generated by Django 2.1.1 on 2019-07-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(db_column='질문', max_length=200)),
                ('sel_1', models.CharField(db_column='보기1', max_length=15)),
                ('sel_2', models.CharField(db_column='보기2', max_length=15)),
                ('sel_3', models.CharField(db_column='보기3', max_length=15)),
                ('sel_4', models.CharField(db_column='보기4', max_length=15)),
                ('sel_5', models.CharField(db_column='보기5', max_length=15)),
                ('sel_6', models.CharField(db_column='보기6', max_length=15)),
                ('sel_7', models.CharField(db_column='보기7', max_length=15)),
                ('sel_8', models.CharField(db_column='보기8', max_length=15)),
                ('sel_9', models.CharField(db_column='보기9', max_length=15)),
            ],
        ),
    ]
