# Generated by Django 2.1.1 on 2019-08-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20190801_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='Bool_overlap',
            field=models.BooleanField(default=False),
        ),
    ]
