# Generated by Django 2.1.1 on 2019-08-09 06:53

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_bool_overlap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit_Poll_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poll_Participant_ID', models.CharField(db_column='작성자', max_length=15)),
                ('Poll_Question', django_mysql.models.JSONField(db_column='질문', default=dict)),
                ('Poll_Answer', django_mysql.models.JSONField(db_column='답변', default=dict)),
                ('Poll_date', models.DateField(auto_now=True, db_column='등록날짜')),
            ],
        ),
    ]
