# Generated by Django 2.1.1 on 2019-08-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_submit_poll_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_poll_table',
            name='Admin_Answer',
            field=models.TextField(blank=True, db_column='관리자답변', null=True),
        ),
    ]
