# Generated by Django 2.1.1 on 2019-08-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_submit_poll_table_admin_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='sel_3',
            field=models.CharField(blank=True, db_column='보기3', default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='sel_4',
            field=models.CharField(blank=True, db_column='보기4', default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='sel_5',
            field=models.CharField(blank=True, db_column='보기5', default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='sel_6',
            field=models.CharField(blank=True, db_column='보기6', default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='sel_7',
            field=models.CharField(blank=True, db_column='보기7', default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='sel_8',
            field=models.CharField(blank=True, db_column='보기8', default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='sel_9',
            field=models.CharField(blank=True, db_column='보기9', default='', max_length=15, null=True),
        ),
    ]
