# Generated by Django 2.1.1 on 2019-08-13 04:37

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20190812_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poll_Participant_ID', models.CharField(db_column='상담자', max_length=15)),
                ('Poll_Condition', django_mysql.models.JSONField(db_column='상세상담조건', default=dict)),
                ('Poll_Question', django_mysql.models.JSONField(db_column='질문', default=dict)),
                ('Bool_overlap', models.BooleanField(default=False)),
                ('Poll_Selection', django_mysql.models.JSONField(db_column='보기', default=dict)),
                ('Poll_Answer', django_mysql.models.JSONField(db_column='답변', default=dict)),
                ('Poll_date', models.DateField(auto_now=True, db_column='등록날짜')),
                ('Admin_Answer', models.TextField(blank=True, db_column='관리자답변', null=True)),
                ('Poll_Result', django_mysql.models.JSONField(db_column='처방내용', default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='submit_poll_table',
            name='Poll_Result',
            field=django_mysql.models.JSONField(db_column='처방제품', default=dict),
        ),
    ]
