# Generated by Django 2.1.1 on 2019-08-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(db_column='아이디', max_length=10)),
                ('Password', models.CharField(db_column='비밀번호', max_length=15)),
                ('Name', models.CharField(db_column='이름', max_length=10)),
                ('Birth', models.DateField(db_column='생년월일')),
                ('Sex', models.TextField(choices=[('man', 'man'), ('woman,', 'woman')], db_column='성별')),
                ('Power', models.BooleanField(db_column='관리자 권한', default=False)),
            ],
        ),
    ]
