# Generated by Django 2.1.1 on 2019-08-13 04:40

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Buy_log',
            field=django_mysql.models.JSONField(db_column='구매내역', default=dict),
        ),
    ]
